web_server:
  port: 80
  auth:
    username: admin
    password: ${password_server}

api:
  encryption:
    key: ${api_key}

logger:
  level: INFO

ota:
  - id: ota_default
    platform: esphome
    password: ${password_ota}


captive_portal:
