web_server:
  port: 80
  auth:
    username: admin
    password: !secret password_server

api:
  encryption:
    key: !secret api_key

logger:
  level: INFO

ota:
  - platform: esphome
    password: !secret password_ota


captive_portal:
