button:
  - platform: restart
    id: restart_btn
    name: "Restart"
    entity_category: "config"
    icon: "mdi:restart"

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: "diagnostic"
    device_class: "connectivity"
