sensor:
  - platform: uptime
    id: esp_uptime
    name: "Uptime"
    # Pozostawiamy w domyślnych sekundach ("s") - brak filtra.
    # Dzięki temu Home Assistant natywnie przechwyci to przez device_class "duration" 
    # i sam sformatuje na ładny, czytelny czas, np: "3 days, 15:20:00"
    update_interval: 60s
    icon: "mdi:timer-outline"
    entity_category: "diagnostic"
    device_class: "duration"
    state_class: "measurement"
    unit_of_measurement: "s"
