sensor:
  - platform: uptime
    id: esp_uptime
    name: "${name} :: uptime"
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
    icon: "mdi:clock-start"
    entity_category: "diagnostic"
