sensor:
  - platform: wifi_signal
    id: inverter_wifi_signal
    name: "${name} :: WiFi Signal"
    update_interval: 60s
    icon: "mdi:wifi"

  - platform: template
    unit_of_measurement: "%"
    name: "${name} :: WiFi Signal"
    accuracy_decimals: 0
    update_interval: 30s
    icon: "mdi:wifi"
    lambda: return (-0.0134 * (id(inverter_wifi_signal).state * id(inverter_wifi_signal).state ) ) + (-0.2228 * id(inverter_wifi_signal).state) + 100.2;
