sensor:
  - platform: wifi_signal
    id: inverter_wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    icon: "mdi:wifi"
    device_class: "signal_strength"
    entity_category: "diagnostic"
    state_class: "measurement"
    unit_of_measurement: "dBm"
